# Generated by Django 4.2.4 on 2023-08-10 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl_app', '0002_shorturl_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='shareable_url',
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='secret_key',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
